This is a testharness.js-based test.
Harness Error. harness_status.status = 1 , harness_status.message = Uncaught Error: Received unknown message
PASS Tests that when timeout is zero (and maximumAge is too), the error callback is called immediately with code TIMEOUT.
Harness: the test ran to completion.

